name: Deploy Jekyll to GH Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Proses merakit file Jekyll menggunakan Docker
      - name: Build Jekyll Site
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      # Hanya mengirim folder _site (hasil rakitan) ke gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # PENTING: Jangan diubah agar tidak mengirim source code
          publish_branch: gh-pages
